server:
  port: 8761

eureka:
  environment: UAT
  datacenter: Phnom Penh
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: eureka-server
